Vagrant.configure("2") do |config|
    config.vm.box = "debian/trixie64"


    config.vm.define "pouetS" do |control| 
        control.vm.hostname = "pouetS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "libvirt" do |libvirt|
            libvirt.memory = 1024
            libvirt.cpus = 1
        end
        control.vm.provision "file", source: "./configs/baby-pod.yml", destination: "/home/vagrant/baby-pod.yml"
        control.vm.provision "file", source: "./configs/baby-pod-dep.yml", destination: "/home/vagrant/baby-pod-dep.yml"
        control.vm.provision "file", source: "./configs/second-dep.yml", destination: "/home/vagrant/second-dep.yml"
        control.vm.provision "shell", path: "script/server.sh"

    end

end
