apiVersion: v1
kind: Service
metadata: 
  name: {{ .Chart.Name }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}