
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume-psql
  labels:
    type: volume-psql
spec:
  storageClassName: shared-storage
  capacity: 
    storage: {{ .Values.persistence.pvSize }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  hostPath:
    path: {{ .Values.persistence.hostMountPathPsql }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.existingClaimPsql }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: shared-storage
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
        type: volume-psql
  resources:
    requests:
      storage: {{ .Values.persistence.pvSize }}