replicaCount: 1 
# nombre de replica de l'app

image: 
  repository: gitlab/gitlab-ce
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  existingClaim: "gitlab-pvc"
  mountPath: "/home/git/repositories"
  hostMountPath: "/mnt/gitlab-data"
  size: 2Gi

