replicaCount: 1 
# nombre de replica de l'app

image: 
  repository: gitlab/gitlab-ce
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  existingClaim: "gitlab-pvc"
  mountPath: "/var/opt/gitlab/git-data"
  hostMountPath: "/mnt/gitlab-data"
  size: 2Gi
  existingDataClaim: "postgresql-pvc"
  mountDataPath: "/var/opt/gitlab/postgresql/data/"
  hostMountDataPath: "/mnt/postgresql-data"
  existingKeyClaim: "gitlab-key-pvc"
  mountKeyPath: "/etc/gitlab/"
  hostMountKeyPath: "/mnt/gitlab-key"

