apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume
  labels: {{- include "gitlab.labels" . | nindent 4 }}
spec:
  storageClassName: shared-storage
  capacity: 
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: {{ .Values.persistence.hostMountPath }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.existingClaim }}
  labels: {{- include "gitlab.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: shared-storage
  accessModes:
    - ReadWriteOnce
  
  resources:
    requests:
      storage: {{ .Values.persistence.half_size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.existingDataClaim }}
  labels: {{- include "gitlab.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: shared-storage
  accessModes:
    - ReadWriteOnce
  
  resources:
    requests:
      storage: {{ .Values.persistence.half_size }}