apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: http://gitlab.gitlab.svc.cluster.local/root/test.git
  username: gitlab+deploy-token-1
  password: gldt-2_6HwBoSJE12_PkEzsre
  type: git