apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: http://gitlab.gitlab.svc.cluster.local/root/test.git
  username: root
  password: gldt-ciShvsuNh45gJUUBs5w6
  type: git